# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

[framework]
simple_name = "dpnp"
full_name = "dpnp"
prefix = "dp"
postfix = "dpnp"
class = "DpnpFramework"
arch = "cpu"
sycl_device = "cpu"

[[framework.postfixes]]
impl_postfix = "dpnp"
description = "dpnp"
