# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

[framework]
simple_name = "numba_dpex"
full_name = "numba_dpex"
prefix = "dpex"
class = "NumbaDpexFramework"
arch = "cpu"
sycl_device = "cpu"

[[framework.postfixes]]
impl_postfix = "numba_dpex_k"
description = "Numba-dpex kernel"

[[framework.postfixes]]
impl_postfix = "numba_dpex_p"
description = "Numba-dpex prange"

[[framework.postfixes]]
impl_postfix = "numba_dpex_n"
description = "Numba-dpex NumPy API"
