# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

[framework]
simple_name = "numba"
full_name = "Numba"
prefix = "nb"
class = "NumbaFramework"
arch = "cpu"
