# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

[benchmark]
name = "Black-Scholes Formula"
short_name = "black-scholes"
relative_path = "black_scholes"
module_name = "black_scholes"
func_name = "black_scholes"
kind = "microbenchmark"
domain = "Finance"
input_args = [
    "nopt",
    "price",
    "strike",
    "t",
    "rate",
    "volatility",
    "call",
    "put",
]
array_args = [
    "price",
    "strike",
    "t",
    "call",
    "put",
]
output_args = [
    "call",
    "put",
]

[benchmark.parameters.S]
nopt = 524288
seed = 777777

[benchmark.parameters.M]
nopt = 134217728
seed = 777777

[benchmark.parameters.L]
nopt = 268435456
seed = 777777

[benchmark.init]
func_name = "initialize"
types_dict_name="types_dict"
precision="double"
input_args = [
    "nopt",
    "seed",
    "types_dict",
]
output_args = [
    "price",
    "strike",
    "t",
    "rate",
    "volatility",
    "call",
    "put",
]
