# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

[benchmark]
name = "Density-based spatial clustering of applications with noise"
short_name = "DBSCAN"
relative_path = "dbscan"
module_name = "dbscan"
func_name = "dbscan"
kind = "microbenchmark"
domain = "Machine Learning"
input_args = [
    "n_samples",
    "n_features",
    "data",
    "eps",
    "min_pts",
]
array_args = [
    "data",
]

[benchmark.parameters.S]
n_samples = 1024
n_features = 10
centers = 10
seed = 777777

[benchmark.parameters.M]
n_samples = 8192
n_features = 10
centers = 10
seed = 777777

[benchmark.parameters.L]
n_samples = 16384
n_features = 10
centers = 10
seed = 777777

[benchmark.init]
func_name = "initialize"
types_dict_name="types_dict"
precision="double"
input_args = [
    "n_samples",
    "n_features",
    "centers",
    "seed",
    "types_dict",
]
output_args = [
    "data",
    "eps",
    "min_pts",
]
