# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

[benchmark]
name = "GPairs"
short_name = "gpairs"
relative_path = "gpairs"
module_name = "gpairs"
func_name = "gpairs"
kind = "microbenchmark"
domain = "Astrophysics"
input_args = [
    "nopt",
    "nbins",
    "x1",
    "y1",
    "z1",
    "w1",
    "x2",
    "y2",
    "z2",
    "w2",
    "rbins",
    "results",
]
array_args = [
    "x1",
    "y1",
    "z1",
    "w1",
    "x2",
    "y2",
    "z2",
    "w2",
    "rbins",
    "results",
]
output_args = [
    "results",
]
expected_failure_implementations = ["numba_dpex_k"]

[benchmark.parameters.S]
nopt = 128
seed = 1234
nbins = 20
rmax = 50
rmin = 0.1

[benchmark.parameters.M16Gb]
nopt = 4096
seed = 1234
nbins = 20
rmax = 50
rmin = 0.1

[benchmark.parameters.M]
nopt = 8192
seed = 1234
nbins = 20
rmax = 50
rmin = 0.1

[benchmark.parameters.L]
nopt = 524288
seed = 1234
nbins = 20
rmax = 50
rmin = 0.1

[benchmark.init]
func_name = "initialize"
types_dict_name="types_dict"
precision="double"
input_args = [
    "nopt",
    "seed",
    "nbins",
    "rmax",
    "rmin",
    "types_dict",
]
output_args = [
    "x1",
    "y1",
    "z1",
    "w1",
    "x2",
    "y2",
    "z2",
    "w2",
    "rbins",
    "results",
]
