# SPDX-FileCopyrightText: 2010-2016 Ohio State University
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "Cholesky Decomposition"
short_name = "cholesky"
relative_path = "cholesky"
module_name = "cholesky"
func_name = "kernel"
kind = "microbench"
domain = "Solver"
dwarf = "dense_linear_algebra"
input_args = [
    "A",
]
array_args = [
    "A",
]
output_args = [
    "A",
]
expected_failure_implementations = ["dpnp"]

[benchmark.parameters.S]
N = 100

[benchmark.parameters.M]
N = 300

[benchmark.parameters.L]
N = 900

[benchmark.parameters.paper]
N = 2000

[benchmark.init]
func_name = "initialize"
input_args = [
    "N",
]
output_args = [
    "A",
]
