# SPDX-FileCopyrightText: 2010-2016 Ohio State University
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "Triangular solver"
short_name = "trisolv"
relative_path = "trisolv"
module_name = "trisolv"
func_name = "kernel"
kind = "microbench"
domain = "Solver"
dwarf = "dense_linear_algebra"
input_args = [
    "L",
    "x",
    "b",
]
array_args = [
    "L",
    "x",
    "b",
]
output_args = [
    "b",
]
expected_failure_implementations = ["dpnp"]

[benchmark.parameters.S]
N = 2000

[benchmark.parameters.M]
N = 5000

[benchmark.parameters.L]
N = 14000

[benchmark.parameters.paper]
N = 16000

[benchmark.init]
func_name = "initialize"
input_args = [
    "N",
]
output_args = [
    "L",
    "x",
    "b",
]
