# SPDX-FileCopyrightText: 2010-2016 Ohio State University
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "General matrix-matrix multiplication"
short_name = "gemm"
relative_path = "gemm"
module_name = "gemm"
func_name = "kernel"
kind = "microbench"
domain = "LinAlg"
dwarf = "dense_linear_algebra"
input_args = [
    "alpha",
    "beta",
    "C",
    "A",
    "B",
]
array_args = [
    "C",
    "A",
    "B",
]
output_args = [
    "C",
]
expected_failure_implementations = ["dpnp"]

[benchmark.parameters.S]
NI = 1000
NJ = 1100
NK = 1200

[benchmark.parameters.M]
NI = 2500
NJ = 2750
NK = 3000

[benchmark.parameters.L]
NI = 7000
NJ = 7500
NK = 8000

[benchmark.parameters.paper]
NI = 2000
NJ = 2300
NK = 2600

[benchmark.init]
func_name = "initialize"
input_args = [
    "NI",
    "NJ",
    "NK",
]
output_args = [
    "alpha",
    "beta",
    "C",
    "A",
    "B",
]
