# SPDX-FileCopyrightText: 2010-2016 Ohio State University
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "Symmetric matrix-multiply"
short_name = "symm"
relative_path = "symm"
module_name = "symm"
func_name = "kernel"
kind = "microbench"
domain = "LinAlg"
dwarf = "dense_linear_algebra"
input_args = [
    "alpha",
    "beta",
    "C",
    "A",
    "B",
]
array_args = [
    "C",
    "A",
    "B",
]
output_args = [
    "C",
]
expected_failure_implementations = ["dpnp"]

[benchmark.parameters.S]
M = 40
N = 50

[benchmark.parameters.M]
M = 120
N = 150

[benchmark.parameters.L]
M = 350
N = 550

[benchmark.parameters.paper]
M = 1000
N = 1200

[benchmark.init]
func_name = "initialize"
input_args = [
    "M",
    "N",
]
output_args = [
    "alpha",
    "beta",
    "C",
    "A",
    "B",
]
