# SPDX-FileCopyrightText: 2010-2016 Ohio State University
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "Symmetric rank-k operations"
short_name = "syrk"
relative_path = "syrk"
module_name = "syrk"
func_name = "kernel"
kind = "microbench"
domain = "LinAlg"
dwarf = "dense_linear_algebra"
input_args = [
    "alpha",
    "beta",
    "C",
    "A",
]
array_args = [
    "C",
    "A",
]
output_args = [
    "C",
]

[benchmark.parameters.S]
M = 50
N = 70

[benchmark.parameters.M]
M = 150
N = 200

[benchmark.parameters.L]
M = 500
N = 600

[benchmark.parameters.paper]
M = 1000
N = 1200

[benchmark.init]
func_name = "initialize"
input_args = [
    "M",
    "N",
]
output_args = [
    "alpha",
    "beta",
    "C",
    "A",
]
