# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

[[implementations]]
impl_postfix = "numba_dpex_k"
description = "Numba-dpex kernel"

[[implementations]]
impl_postfix = "numba_dpex_p"
description = "Numba-dpex prange"

[[implementations]]
impl_postfix = "numba_dpex_n"
description = "Numba-dpex NumPy API"

[[implementations]]
impl_postfix = "dpnp"
description = "dpnp"

[[implementations]]
impl_postfix = "numpy"
description = "NumPy"

[[implementations]]
impl_postfix = "python"
description = "Python"

[[implementations]]
impl_postfix = "numba_n"
description = "Numba nopython"

[[implementations]]
impl_postfix = "numba_np"
description = "Numba nopython, Parallel=True"

[[implementations]]
impl_postfix = "numba_npr"
description = "Numba nopython, Parallel=True, prange"

[[implementations]]
impl_postfix = "sycl"
description = "DPC++ native ext."
