# SPDX-FileCopyrightText: 2010-2016 Ohio State University
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "2-D Jacobi stencil computation"
short_name = "jacobi2d"
relative_path = "jacobi_2d"
module_name = "jacobi_2d"
func_name = "kernel"
kind = "microbench"
domain = "Physics"
dwarf = "structured_grids"
input_args = [
    "TSTEPS",
    "A",
    "B",
]
array_args = [
    "A",
    "B",
]
output_args = [
    "A",
    "B",
]

[benchmark.parameters.S]
TSTEPS = 50
N = 150

[benchmark.parameters.M]
TSTEPS = 80
N = 350

[benchmark.parameters.L]
TSTEPS = 200
N = 700

[benchmark.parameters.paper]
TSTEPS = 1000
N = 2800

[benchmark.init]
func_name = "initialize"
input_args = [
    "N",
]
output_args = [
    "A",
    "B",
]
