# SPDX-FileCopyrightText: 2014 Jérôme Kieffer et al.
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "Azimuthal Integration - Histogram"
short_name = "azimhist"
relative_path = "azimint_hist"
module_name = "azimint_hist"
func_name = "azimint_hist"
kind = "microapp"
domain = "Physics"
dwarf = "spectral_methods"
input_args = [
    "data",
    "radius",
    "npt",
]
array_args = [
    "data",
    "radius",
]
output_args = []
expected_failure_implementations = ["dpnp"]

[benchmark.parameters.S]
N = 400000
npt = 1000

[benchmark.parameters.M]
N = 4000000
npt = 1000

[benchmark.parameters.L]
N = 40000000
npt = 1000

[benchmark.parameters.paper]
N = 1000000
npt = 1000

[benchmark.init]
func_name = "initialize"
input_args = [
    "N",
]
output_args = [
    "data",
    "radius",
]
