# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "Conv2D with Bias"
short_name = "conv2d"
relative_path = "deep_learning/conv2d_bias"
module_name = "conv2d_bias"
func_name = "conv2d_bias"
kind = "microbench"
domain = "Learning"
dwarf = "dense_linear_algebra"
input_args = [
    "input",
    "weights",
    "bias",
]
array_args = [
    "input",
    "weights",
    "bias",
]
output_args = []
expected_failure_implementations = ["dpnp"]

[benchmark.parameters.S]
N = 8
C_in = 3
C_out = 16
K = 2
H = 32
W = 32

[benchmark.parameters.M]
N = 8
C_in = 3
C_out = 8
K = 5
H = 64
W = 64

[benchmark.parameters.L]
N = 8
C_in = 3
C_out = 8
K = 10
H = 128
W = 128

[benchmark.parameters.paper]
N = 8
C_in = 3
C_out = 16
K = 20
H = 256
W = 256

[benchmark.init]
func_name = "initialize"
input_args = [
    "C_in",
    "C_out",
    "H",
    "K",
    "N",
    "W",
]
output_args = [
    "input",
    "weights",
    "bias",
]
