# SPDX-FileCopyrightText: 2014-2021 ETH Zurich
# SPDX-FileCopyrightText: 2007 Free Software Foundation, Inc. <https://fsf.org/>
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: GPL-3.0-or-later

[benchmark]
name = "Horizontal Diffusion"
short_name = "hdiff"
relative_path = "weather_stencils/hdiff"
module_name = "hdiff"
func_name = "hdiff"
kind = "microapp"
domain = "Weather"
dwarf = "structured_grids"
input_args = [
    "in_field",
    "out_field",
    "coeff",
]
array_args = [
    "in_field",
    "out_field",
    "coeff",
]
output_args = [
    "out_field",
]
expected_failure_implementations = ["dpnp"]

[benchmark.parameters.S]
I = 64
J = 64
K = 60

[benchmark.parameters.M]
I = 128
J = 128
K = 160

[benchmark.parameters.L]
I = 384
J = 384
K = 160

[benchmark.parameters.paper]
I = 256
J = 256
K = 160

[benchmark.init]
func_name = "initialize"
input_args = [
    "I",
    "J",
    "K",
]
output_args = [
    "in_field",
    "out_field",
    "coeff",
]
