# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "Stockham FFT"
short_name = "sthamfft"
relative_path = "stockham_fft"
module_name = "stockham_fft"
func_name = "stockham_fft"
kind = "microbench"
domain = "Other"
dwarf = "spectral_methods"
input_args = [
    "N",
    "R",
    "K",
    "x",
    "y",
]
array_args = [
    "x",
    "y",
]
output_args = [
    "y",
]
expected_failure_implementations = ["dpnp"]

[benchmark.parameters.S]
R = 2
K = 15

[benchmark.parameters.M]
R = 2
K = 18

[benchmark.parameters.L]
R = 2
K = 21

[benchmark.parameters.paper]
R = 4
K = 10

[benchmark.init]
func_name = "initialize"
input_args = [
    "R",
    "K",
]
output_args = [
    "N",
    "x",
    "y",
]
